((stocks
  (((symbol BEST) (name "BEST Inc. (BEST)") (price 2.69) (growth 6.96)
    (sector Industrials) (industry Trucking)
    (summary
     "BEST Inc. operates as a smart supply chain service provider in the People's Republic of China. Its proprietary technology platform, BEST Cloud, enables its ecosystem participants to operate their businesses through various SaaS-based applications. The company applies its technologies to a range of applications, such as network and route optimization, swap bodies, sorting line automation, smart warehouses, and store management. In addition, it offers integrated services and solutions across the supply chain, including warehouse management, order fulfillment, and transportation services to offline and online enterprises. Further, the company provides express delivery services; and door-to-door integrated cross-border supply chain services to and from China, including international express, less-than-truckload, fulfillment, and freight forwarding through its network, and transportation and warehouse partners. Additionally, it operates real-time bidding platform to source truckload capacity from independent transportation service providers and agents; and offers online merchandise sourcing and store management services for convenience stores, as well as B2C services. Furthermore, the company provides various value-added services, including pre-shipment inspection, cargo insurance, oversized item delivery, COD facilitation, evidence of delivery, and upstairs delivery services. The company was founded in 2007 and is headquartered in Hangzhou, the People's Republic of China.")
    (headlines ("")) (profit_margin -17.6) (gross_profit -263.56M)
    (diluted_eps -9.88))
   ((symbol GCI) (name "Gannett Co., Inc. (GCI)") (price 3.52) (growth 9.32)
    (sector "Communication Services") (industry Publishing)
    (summary
     "Gannett Co., Inc. operates as a media and marketing solutions company in the United States. It operates through two segments, Gannett Media and Digital Marketing Solutions. The company's principal products include 218 daily print media with total paid circulation of approximately 1.6 million and Sunday circulation of 4.1 million; 175 weekly print media; and 266 locally-focused websites. Its principal products also comprise 154 daily and weekly news media brands and approximately 90 magazines, and related digital platforms; sports network; and USA TODAY NETWORK, a community events platform. The company also offers digital marketing solutions, such as online presence solutions, online advertising products, conversion software, and cloud-based software solutions. In addition, it produces niche publications that address specific local market interests, such as recreation, sports, healthcare, and real estate. Further, the company offers local market news and information, as well as advertising and subscriptions, and commercial printing and distribution services; and prints commercial materials, including flyers, business cards, and invitations. The company was formerly known as New Media Investment Group Inc. and changed its name to Gannett Co., Inc. in November 2019. Gannett Co., Inc. was incorporated in 2013 and is headquartered in McLean, Virginia.")
    (headlines ("")) (profit_margin 0) (gross_profit 1.08B)
    (diluted_eps -0.46))
   ((symbol ATIP) (name "ATI Physical Therapy, Inc. (ATIP)") (price 7.92)
    (growth 5.74) (sector Healthcare) (industry "Medical Care Facilities")
    (summary
     "ATI Physical Therapy, Inc. operates as an outpatient physical therapy provider that specializes in outpatient rehabilitation and adjacent healthcare services in the United States. It offers a range of services to its patients, including physical therapy to treat spine, shoulder, knee, and neck injuries or pain; work conditioning and work hardening; and hand therapy, aquatic therapy, functional capacity assessment, and wellness programs. It also provides ATI worksite solutions comprising injury prevention programs, work-related injury assessment services, wellness offerings, and consultations for employers; proprietary electronic medical records (EMR) integration, caseload management, and continuing education in progressive therapies; and sports medicine, including onsite sports physical therapy, clinical evaluation and diagnosis, immediate and emergency care, nutrition programs, and concussion management services. The company offers outpatient physical therapy services under the ATI Physical Therapy name. ATI Physical Therapy, Inc. was founded in 1996 and is based in Bolingbrook, Illinois.")
    (headlines ("")) (profit_margin -59.9) (gross_profit 263.82M)
    (diluted_eps -92.34))
   ((symbol SBH) (name "Sally Beauty Holdings, Inc. (SBH)") (price 12.18)
    (growth 7.12) (sector "Consumer Cyclical") (industry "Specialty Retail")
    (summary
     "Sally Beauty Holdings, Inc. operates as a specialty retailer and distributor of professional beauty supplies. The company operates through two segments, Sally Beauty Supply and Beauty Systems Group. The Sally Beauty Supply segment offers beauty products, including hair color and care products, skin and nail care products, styling tools, and other beauty products for retail customers, salons, and salon professionals. This segment also provides products under third-party brands, such as Wella, Clairol, OPI, Conair, and L'Oreal, as well as exclusive-label brand merchandise. The Beauty Systems Group segment offers professional beauty products, such as hair color and care products, skin and nail care products, styling tools, and other beauty items directly to salons and salon professionals through its professional-only stores, e-commerce platforms, and sales force, as well as through franchised stores under the Armstrong McCall store name. This segment also sells products under third-party brands, such as Paul Mitchell, Wella, Matrix, Schwarzkopf, Kenra, Goldwell, Joico, and Olaplex. It operates stores and franchised units in the United States, Puerto Rico, Canada, Mexico, Chile, Peru, the United Kingdom, Ireland, Belgium, France, the Netherlands, Spain, and Germany. It also distributes its products through full-service/exclusive distributors, open-line distributors, direct sales, and mega-salon stores. Sally Beauty Holdings, Inc. was founded in 1964 and is headquartered in Denton, Texas.")
    (headlines ("")) (profit_margin 4.3) (gross_profit 1.94B)
    (diluted_eps 1.51))
   ((symbol HPP) (name "Hudson Pacific Properties, Inc. (HPP)") (price 6.55)
    (growth 8.62) (sector "Real Estate") (industry "REIT\226\128\148Office")
    (summary
     "Hudson Pacific Properties (NYSE: HPP) is a real estate investment trust serving dynamic tech and media tenants in global epicenters for these synergistic, converging and secular growth industries. Hudson Pacific's unique and high-barrier tech and media focus leverages a full-service, end-to-end value creation platform forged through deep strategic relationships and niche expertise across identifying, acquiring, transforming and developing properties into world-class amenitized, collaborative and sustainable office and studio space.")
    (headlines ("")) (profit_margin -6.2) (gross_profit 607.69M)
    (diluted_eps -0.4))
   ((symbol NKTR) (name "Nektar Therapeutics (NKTR)") (price 1.02)
    (growth 91.51) (sector Healthcare) (industry Biotechnology)
    (summary
     "Nektar Therapeutics, a biopharmaceutical company, focuses on discovering and developing medicines in the field of immunotherapy in the United States and internationally. The company is developing rezpegaldesleukin, a cytokine Treg stimulant that is in phase 2 clinical trial for the treatment of systemic lupus erythematosus and ulcerative colitis, as well as phase 1B clinical trial to treat atopic dermatitis and psoriasis; and NKTR-255, an IL-15 receptor agonist, which is in phase 1/2 clinical trial for the treatment of non-Hodgkin's lymphoma and multiple myeloma, and head and neck cancer squamous cell carcinoma and colorectal cancer. It has collaboration agreements with Takeda Pharmaceutical Company Ltd.; AstraZeneca AB; UCB Pharma S.A.; F. Hoffmann-La Roche Ltd; Bausch Health Companies Inc.; Pfizer Inc.; Amgen Inc.; UCB Pharma (Biogen); Bristol-Myers Squibb Company; Baxalta Incorporated; Eli Lilly and Company; Merck KGaA; and SFJ Pharmaceuticals, Inc.  The company was incorporated in 1990 and is headquartered in San Francisco, California.")
    (headlines ("")) (profit_margin 0) (gross_profit 70.42M)
    (diluted_eps -2.29))
   ((symbol DHC) (name "Diversified Healthcare Trust (DHC)") (price 2.97)
    (growth 10) (sector "Real Estate")
    (industry "REIT\226\128\148Healthcare Facilities")
    (summary
     "DHC is a real estate investment trust focused on owning high-quality healthcare properties located throughout the United States. DHC seeks diversification across the health services spectrum by care delivery and practice type, by scientific research disciplines and by property type and location. As of June 30, 2023, DHC's approximately $7.1 billion portfolio included 376 properties in 36 states and Washington, D.C., occupied by approximately 500 tenants, and totaling approximately 9 million square feet of life science and medical office properties and more than 27,000 senior living units. DHC is managed by The RMR Group (Nasdaq: RMR), a leading U.S. alternative asset management company with approximately $36 billion in assets under management as of June 30, 2023 and more than 35 years of institutional experience in buying, selling, financing and operating commercial real estate. DHC is headquartered in Newton, MA.")
    (headlines ("")) (profit_margin -20.1) (gross_profit 171.89M)
    (diluted_eps -1.3))
   ((symbol TDUP) (name "ThredUp Inc. (TDUP)") (price 3.54) (growth 7.27)
    (sector "Consumer Cyclical") (industry "Internet Retail")
    (summary
     "ThredUp Inc., together with its subsidiaries, operates an online resale platform in the United States and internationally. Its platform enables consumers to buy and sell primarily secondhand women's and kids' apparel, shoes, and accessories. ThredUp Inc. was incorporated in 2009 and is headquartered in Oakland, California.")
    (headlines ("")) (profit_margin -31.3) (gross_profit 192.34M)
    (diluted_eps -0.87))
   ((symbol ADV) (name "Advantage Solutions Inc. (ADV)") (price 2.65)
    (growth 11.81) (sector "Communication Services")
    (industry "Advertising Agencies")
    (summary
     "Advantage Solutions Inc. provides outsourced solutions to consumer goods companies and retailers in North America and internationally. It operates in two segments, Sales and Marketing. The Sales segment offers brand-centric services, such as headquarter relationship management; analytics, insights, and intelligence; administration; and brand-centric merchandising services. This segment also provides retailer-centric services comprising retailer-centric merchandising, in-store media, and digital commerce. The Marketing segment offers brand-centric services, including shopper and consumer marketing, and brand experiential services; and retailer-centric services, such as retail experiential, private label, digital marketing, and digital media and advertising. The company was formerly known as Karman Holding Corp. and changed its name to Advantage Solutions Inc. in March 2016. The company was founded in 1987 and is headquartered in Irvine, California.")
    (headlines ("")) (profit_margin -34.7) (gross_profit 556.56M)
    (diluted_eps -4.7))
   ((symbol OSUR) (name "OraSure Technologies, Inc. (OSUR)") (price 6.4)
    (growth 7.74) (sector Healthcare)
    (industry "Medical Instruments & Supplies")
    (summary
     "OraSure Technologies, Inc., together with its subsidiaries, provides point-of-care and home diagnostic tests, specimen collection devices, and microbiome laboratory and analytical services in the United States, Europe, and internationally. It operates in two segments, Diagnostics and Molecular Solutions. The company's diagnostic products include InteliSwab COVID-19 rapid test, InteliSwab COVID-19 rapid test pro, InteliSwab COVID-19 rapid test rx, OraQuick Rapid HIV test, OraQuick In-Home HIV test, OraQuick HIV self-test, OraQuick HCV rapid antibody test, OraQuick Ebola rapid antigen test, OraSure oral fluid collection device used in conjunction with screening and confirmatory tests for HIV-1 antibodies; Intercept drug testing systems; immunoassay tests and reagents; and Q.E.D. saliva alcohol test. It also offers genomic products under the Oragene and ORAcollect brands for collecting genetic material from human saliva; Colli-Pee collection devices for the volumetric collection of void urine samples; and microbiome laboratory testing and analytical services. In addition, the company provides microbiome products, such as OMNIgene \194\149 GUT for self-collecting microbial DNA from feces or stool samples for gut microbiome profiling; OMNIgene \194\149 GUT DNA and RNA collection devices; and OMNIgene\194\149GUT Dx collection device for collection of human fecal samples and the stabilization of DNA from the bacterial community. Additionally, it provides other diagnostic products, such as immunoassays and other in vitro diagnostic tests. The company markets its products to clinical laboratories, hospitals, clinics, community-based organizations and other public health organizations, distributors, government agencies, physicians' offices, commercial and industrial entities, disease risk management, diagnostics, pharmaceutical, biotech, nutrition, companion animal, and environmental markets. OraSure Technologies, Inc. was incorporated in 2000 and is based in Bethlehem, Pennsylvania.")
    (headlines ("")) (profit_margin 8.9) (gross_profit 147.64M)
    (diluted_eps 0.41))
   ((symbol AMRX) (name "Amneal Pharmaceuticals, Inc. (AMRX)") (price 4.59)
    (growth 11.68) (sector Healthcare)
    (industry "Drug Manufacturers\226\128\148Specialty & Generic")
    (summary
     "Amneal Pharmaceuticals, Inc., together with its subsidiaries, develops, manufactures, markets, and distributes generics, injectables, biosimilars, and specialty branded pharmaceutical products worldwide. The company operates through three segments: Generics, Specialty, and AvKARE. The Generics segment offers immediate and extended release oral solid, powder, liquid, sterile injectable, nasal spray, inhalation and respiratory, biosimilar, ophthalmic, film, transdermal patch, and topical products. The Specialty segment develops, promotes, sells, and distributes pharmaceutical products with focus on central nervous system disorders, including Parkinson's disease, and endocrine disorders. This segment also provides Rytary, an oral capsule formulation of carbidopa-levodopa to treat Parkinson's disease, post-encephalitic parkinsonism, and parkinsonism; Unithroid for the treatment of hypothyroidism; and IPX203, a pipeline product for Parkinson's disease. The AvKARE segment offers pharmaceuticals, medical and surgical products, and services primarily to governmental agencies, the Department of Defense, and the Department of Veterans Affairs. This segment also distributes bottle and unit dose pharmaceuticals under the AvKARE and AvPAK names; and packages and distributes pharmaceuticals and vitamins to its retail and institutional customers. It sells its products through wholesalers, distributors, hospitals, chain pharmacies, and individual pharmacies. The company was formerly known as Atlas Holdings, Inc. and changed its name to Amneal Pharmaceuticals, Inc. in 2018. Amneal Pharmaceuticals, Inc. was founded in 2002 and is headquartered in Bridgewater, New Jersey.")
    (headlines ("")) (profit_margin -5.9) (gross_profit 791.46M)
    (diluted_eps -0.83))
   ((symbol EB) (name "Eventbrite, Inc. (EB)") (price 11.87) (growth 5.51)
    (sector Technology) (industry "Software\226\128\148Application")
    (summary
     "Eventbrite, Inc. operates a self-service ticketing and experience technology platform that serves event creators in the United States and internationally. Its platform integrates components needed to plan, promote, and produce live events that allow creators to reduce friction and costs, enhance reach, and drive ticket sales. The company was formerly known as Mollyguard Corporation and changed its name to Eventbrite, Inc. in 2009. Eventbrite, Inc. was incorporated in 2008 and is headquartered in San Francisco, California.")
    (headlines ("")) (profit_margin -11) (gross_profit 170.18M)
    (diluted_eps -0.49))
   ((symbol NUVB) (name "Nuvation Bio Inc. (NUVB)") (price 1.95)
    (growth 5.98) (sector Healthcare) (industry Biotechnology)
    (summary
     "Nuvation Bio Inc., a clinical-stage biopharmaceutical company, focuses on the development of therapeutic candidates for oncology. The company's lead product candidate is NUV-868, a selective oral small molecule BET inhibitor that epigenetically regulates proteins that control tumor growth and differentiation, including oncogenes comprising c-myc; NUV-1156, an AR binder Xtandi that address advanced stage prostate cancers with the potential to move into earlier lines typically treated with surgical prostatectomy; and drug-drug conjugate (DDC) platform that focuses on targeting an inhibitor of poly ADP ribose polymerase (PARP) to anti-cancer warheads of existing drugs, as well as NUV-1176, a PARP inhibitor to address ER+ breast and ovarian cancer. Nuvation Bio Inc. was founded in 2018 and is headquartered in New York, New York.")
    (headlines ("")) (profit_margin 0) (gross_profit N/A)
    (diluted_eps -0.45))
   ((symbol EVLO) (name "Evelo Biosciences, Inc. (EVLO)") (price 10.69)
    (growth 10.43) (sector Healthcare) (industry Biotechnology)
    (summary
     "Evelo Biosciences, Inc., a clinical-stage biotechnology company, focuses on discovering and developing oral medicines that act on immune cells in the small intestine with systemic effects. It is developing EDP1815, a whole-microbe product candidate, which has completed a Phase 2 trial for the treatment of psoriais; and is in Phase 2 clinical trial for the treatment of atopic dermatitis. The company is also developing EDP1867, a non-live pharmaceutical preparation for single strain of Veillonella parvula, which is in Phase 1b clinical trial; EDP2939, an investigational oral biologic for the potential treatment of inflammatory diseases; and EDP1908, a product candidate for oncology. Evelo Biosciences, Inc. was incorporated in 2014 and is headquartered in Cambridge, Massachusetts.")
    (headlines ("")) (profit_margin 0) (gross_profit N/A)
    (diluted_eps -18.77))
   ((symbol OPI) (name "Office Properties Income Trust (OPI)") (price 8.1)
    (growth 9.02) (sector "Real Estate") (industry "REIT\226\128\148Office")
    (summary
     "OPI is a national REIT focused on owning and leasing high quality office and mixed-use properties in select growth-oriented U.S. markets. As of June 30, 2023, approximately 63% of OPI's revenues were from investment grade rated tenants. OPI owned and leased 155 properties as of June 30, 2023, with approximately 20.8 million square feet located in 30 states and Washington, D.C. In 2023, OPI was named as an Energy Star Partner of the Year for the sixth consecutive year. OPI is managed by The RMR Group (Nasdaq: RMR), a leading U.S. alternative asset management company with approximately $36 billion in assets under management as of June 30, 2023, and more than 35 years of institutional experience in buying, selling, financing and operating commercial real estate. OPI is headquartered in Newton, MA.")
    (headlines ("")) (profit_margin 2) (gross_profit 469.43M)
    (diluted_eps 0.13))
   ((symbol SATS) (name "EchoStar Corporation (SATS)") (price 23.5)
    (growth 21.26) (sector Technology) (industry "Communication Equipment")
    (summary
     "EchoStar Corporation, together with its subsidiaries, provides networking technologies and services worldwide. The company operates in two segments, Hughes and EchoStar Satellite Services (ESS). The Hughes segment offers broadband network technologies, managed services, equipment, hardware, satellite services, and communications solutions to government and enterprise customers. The segment also designs, provides, and installs gateway and terminal equipment to customers for other satellite systems, as well as offers satellite ground segment systems and terminals for other satellite systems, including mobile system operators. In addition, it designs, develops, constructs, and provides telecommunication networks comprising satellite ground segment systems and terminals to mobile system operators and enterprise customers. The ESS segment provides satellite services using its owned and leased to offer satellite services on a full-time and/or occasional-use basis to the U.S. government service providers, internet service providers, broadcast news organizations, content providers, and private enterprise customers. It serves customers in North America, South and Central America, Asia, Africa, Australia, Europe, India, and the Middle East. The company was incorporated in 2007 and is headquartered in Englewood, Colorado.")
    (headlines ("")) (profit_margin 5.9) (gross_profit 1.14B)
    (diluted_eps 1.37))
   ((symbol MAXN) (name "Maxeon Solar Technologies, Ltd. (MAXN)")
    (price 23.16) (growth 5.08) (sector Technology) (industry Solar)
    (summary
     "Maxeon Solar Technologies, Ltd. designs, manufactures, markets, and sells solar panels and related solar system components worldwide. The company provides interdigitated back contact and shingled solar cells and panels under the SunPower brand. It offers its products to dealers, project developers, system integrators, distributors, resellers, and residential and small-scale commercial customers. The company was incorporated in 2019 and is headquartered in Singapore.")
    (headlines ("")) (profit_margin -16.2) (gross_profit -32.78M)
    (diluted_eps -4.83))
   ((symbol TUP) (name "Tupperware Brands Corporation (TUP)") (price 5.23)
    (growth 9.64) (sector "Consumer Cyclical")
    (industry "Packaging & Containers")
    (summary
     "Tupperware Brands Corporation operates as a consumer products company worldwide. The company manufactures, markets, and sells design-centric preparation, storage, and serving solutions for the kitchen and home, as well as a line of cookware, knives, microwave products, microfiber textiles, water-filtration related items, and an array of products for on-the-go consumers under the Tupperware brand name. It distributes its products to approximately 70 countries primarily through independent sales force members, including independent distributors, directors, managers, and dealers. The company was formerly known as Tupperware Corporation and changed its name to Tupperware Brands Corporation in December 2005. Tupperware Brands Corporation was founded in 1946 and is headquartered in Orlando, Florida.")
    (headlines ("")) (profit_margin -1) (gross_profit 836.4M)
    (diluted_eps -0.52))
   ((symbol PSTX) (name "Poseida Therapeutics, Inc. (PSTX)") (price 1.98)
    (growth 21.47) (sector Healthcare) (industry Biotechnology)
    (summary
     "Poseida Therapeutics, Inc., a clinical-stage biopharmaceutical company, focuses on developing therapeutics for patients with high unmet medical needs. The company develops P-PSMA-ALLO1, an autologous chimeric antigen receptor T cell (CAR-T) product candidate that is in Phase I trial for the treatment of patients with metastatic castrate resistant prostate cancer (mCRPC). It is also developing P-BCMA-ALLO1, which is in Phase I trial to treat patients with relapsed/refractory multiple myeloma; and P-MUC1C-ALLO1 that is in Phase I trial for treating a range of solid tumors, including breast, colorectal, lung, ovarian, pancreatic, and renal cancers. In addition, the company engages in the development of P-CD19CD20-ALLO1 for B cell malignancies and other autoimmune diseases; and P-BCMACD19-ALLO1, an allogeneic, off-the-shelf CAR-T product candidate in preclinical development for multiple myeloma. Further, it is developing P-PSMA-101, an allogeneic CAR-T product candidate for treating mCRPC. Additionally, the company engages in the development of P-OTC-101, a liver-directed gene therapy for the in vivo treatment of ornithine transcarbamylase deficiency; P-FVIII-101, a clinical stage liver-directed gene therapy for the in vivo treatment of hemophilia A; and P-PAH-101, a liver-directed gene therapy for the in vivo treatment of phenylketonuria. Poseida Therapeutics, Inc. has a research collaboration and license agreement with Takeda Pharmaceuticals USA, Inc., F. Hoffmann-La Roche Ltd, and Hoffmann-La Roche Inc. The company was incorporated in 2014 and is headquartered in San Diego, California.")
    (headlines ("")) (profit_margin -32.1) (gross_profit -22.41M)
    (diluted_eps -0.36))
   ((symbol SBOW) (name "SilverBow Resources, Inc. (SBOW)") (price 38.91)
    (growth 5.13) (sector Energy) (industry "Oil & Gas E&P")
    (summary
     "SilverBow Resources, Inc., an oil and gas company, engages in exploration, development, acquisition, and operation of oil and natural gas properties in the Eagle Ford shale and Austin Chalk located in South Texas. The company was formerly known as Swift Energy Company and changed its name to SilverBow Resources, Inc. in May 2017. SilverBow Resources, Inc. was founded in 1979 and is headquartered in Houston, Texas.")
    (headlines ("")) (profit_margin 61.5) (gross_profit 679.68M)
    (diluted_eps 25.16))
   ((symbol PRDO) (name "Perdoceo Education Corporation (PRDO)")
    (price 16.99) (growth 6.65) (sector "Consumer Defensive")
    (industry "Education & Training Services")
    (summary
     "Perdoceo Education Corporation provides postsecondary education through online, campus-based, and blended learning programs in the United States. The company operates in two segments, Colorado Technical University and The American InterContinental University System. It offers academic programs in the career-oriented disciplines of business and management, nursing, healthcare management, computer science, engineering, information systems and technology, project management, cybersecurity, and criminal justice, as well as business studies, information technologies, education, and health sciences. The company also operates intellipath, a personalized learning platform; and a mobile application and two-way messaging platform. The company was formerly known as Career Education Corporation and changed its name to Perdoceo Education Corporation in January 2020. The company was incorporated in 1994 and is based in Schaumburg, Illinois.")
    (headlines ("")) (profit_margin 17.5) (gross_profit 595.8M)
    (diluted_eps 1.43))
   ((symbol HLLY) (name "Holley Inc. (HLLY)") (price 6.74) (growth 10.13)
    (sector "Consumer Cyclical") (industry "Auto Parts")
    (summary
     "Holley Inc. designs, manufactures, and markets automotive aftermarket products for car and truck enthusiasts in the United States, Canada, Europe, and China. The company's products include carburetors, fuel pumps, fuel injection systems, nitrous oxide injection systems, superchargers, exhaust headers, mufflers, distributors, ignition components, engine tuners, automotive performance plumbing products, and exhaust products as well as shifters, converters, transmission kits, transmissions, tuners, and automotive software. It also offers wheels, chassis and suspension products, helmets, head and neck restraints, seat belts, fire suits, and electronic control and monitoring systems. The company sells its products under the Holley, Holley EFI, APR, MSD, Flowmaster, Powerteq, Accel, and Simpson brands to retailers directly, as well as through distributors and online platform. The company was founded in 1903 and is headquartered in Bowling Green, Kentucky.")
    (headlines ("")) (profit_margin 9.2) (gross_profit 258.18M)
    (diluted_eps 0.03))
   ((symbol QUAD) (name "Quad/Graphics, Inc. (QUAD)") (price 5.96)
    (growth 5.49) (sector Industrials)
    (industry "Specialty Business Services")
    (summary
     "Quad/Graphics, Inc. provides marketing solutions worldwide. The company operates through United States Print and Related Services, and International segments. It offers printing services, such as retail inserts, publications, catalogs, special interest publications, journals, direct mail, directories, in-store marketing and promotion, packaging, newspapers, custom print products, and other commercial and specialty printed products; and paper procurement services. The company also provides marketing and other services, including data and analytics, technology solutions, media services, creative and content solutions, managed services, and execution in non-print channels, as well as manufactures ink. It serves blue chip companies that operate in various industries, and serve businesses and consumers comprising retailers, publishers, and direct marketers. The company was founded in 1971 and is headquartered in Sussex, Wisconsin.")
    (headlines ("")) (profit_margin -0.8) (gross_profit 598.2M)
    (diluted_eps -0.31))
   ((symbol FRGI) (name "Fiesta Restaurant Group, Inc. (FRGI)") (price 8.38)
    (growth 6.62) (sector "Consumer Cyclical") (industry Restaurants)
    (summary
     "Fiesta Restaurant Group, Inc., together with its subsidiaries, owns, operates, and franchises fast-casual restaurants. It operates its fast-casual restaurants under the Pollo Tropical brand. The company's Pollo Tropical restaurants offer fire-grilled and citrus marinated chicken, and other freshly prepared tropical inspired menu items. The company owns Pollo Tropical restaurants in Florida and franchised Pollo Tropical restaurants in the Puerto Rico, Panama, Guyana, Bahamas, Ecuador, and Florida. Fiesta Restaurant Group, Inc. was incorporated in 2011 and is based in Dallas, Texas.")
    (headlines ("")) (profit_margin -3.8) (gross_profit 73.53M)
    (diluted_eps -0.63))
   ((symbol ACOR) (name "Acorda Therapeutics, Inc. (ACOR)") (price 17.6)
    (growth 14.58) (sector Healthcare)
    (industry "Drug Manufacturers\226\128\148Specialty & Generic")
    (summary
     "Acorda Therapeutics, Inc., a biopharmaceutical company, develops and commercializes therapies for neurological disorders in the United States. The company markets Ampyra (dalfampridine), an oral drug to improve walking in adults with multiple sclerosis; and Inbrija, an inhaled levodopa for intermittent treatment of OFF periods in people with Parkinson's disease treated with a carbidopa/levodopa regimen. It also markets Ampyra as Fampyra in Europe, Asia, and the Americas. The company's product pipeline includes Cimaglermin alfa (GGF2), a member of neuregulin growth factor family which is in Phase 1 clinical trials for recovery of neurological injury, as well as to enhance heart function in animal models of heart failure. In addition, it has collaboration and license agreement with Biogen Inc. for the development and commercialization of Ampyra. The company was incorporated in 1995 and is headquartered in Pearl River, New York.")
    (headlines ("")) (profit_margin -49.2) (gross_profit 82.43M)
    (diluted_eps -40.53))
   ((symbol KUKE) (name "Kuke Music Holding Limited (KUKE)") (price 0.5445)
    (growth 9.34) (sector "Communication Services") (industry Entertainment)
    (summary
     "Kuke Music Holding Limited, through its subsidiaries, provides classical music licensing, subscription, and education services in China. It operates through two segments: Subscription, Licensing and Smart Education Business; and Music Events and Performances Business. The Subscription, Licensing and Smart Education Business segment distributes commercial copyrights and offers music education solutions. The Music Events Business segment provides music festival events and music performance services; and sells musical instruments, including conch smart speakers. The company licenses its music content primarily to online music entertainment platforms, digital music service providers, and commercial enterprises, as well as film and TV production companies, airlines, and smart hardware companies. It has institutional subscribers, including universities and music conservatories, as well as public libraries. Kuke Music Holding Limited was founded in 2002 and is headquartered in Beijing, China.")
    (headlines ("")) (profit_margin 0) (gross_profit 9.47M)
    (diluted_eps -4.09))
   ((symbol SQNS) (name "Sequans Communications S.A. (SQNS)") (price 2.79)
    (growth 30.99) (sector Technology) (industry Semiconductors)
    (summary
     "Sequans Communications S.A. engages in the fabless designing, developing, and supplying of cellular semiconductor solutions for massive and broadband Internet of Things (IoT) markets in Taiwan, Korea, China, rest of Asia, Germany, the United States, and internationally. It offers baseband solutions for use in encoding and decoding data based on 4G and 5G protocols for wireless processing platform for a cellular device; RF transceivers used to transmit and receive wireless transmissions; highly integrated SoC solutions that combine various functions into a single die or package; and LTE modules. The company also provides software, including source code and tools to enable manufacturers to integrate their solutions into their devices; and design support services. The company serves OEMs and ODMs Customers, as well as 4G and 5G wireless carriers. Sequans Communications S.A. was incorporated in 2003 and is based in Paris, France.")
    (headlines ("")) (profit_margin -27.4) (gross_profit 42.88M)
    (diluted_eps -0.35))
   ((symbol ARC) (name "ARC Document Solutions, Inc. (ARC)") (price 3.5)
    (growth 5.74) (sector Industrials)
    (industry "Specialty Business Services")
    (summary
     "ARC Document Solutions, Inc., a digital printing company, provides digital printing and document-related services in the United States. It provides managed print services, that places, manages, and optimizes print and imaging equipment in customers' offices, job sites, and other facilities; and cloud-based document management software and other digital hosting services. The company also provides professional services and software services to re-produce and distribute large-format and small-format documents, and specialized graphic color printing. In addition, it engages in sale and supply of equipment; and provides ancillary services. The company operates service centers in the United States, Canada, China, United Kingdom, India, United Arab Emirates. It serves local restaurant owners, construction subcontractors, international retailers, regional energy companies, and largest school districts, as well as retail, technology, energy, education, hospitality, public utilities, and others. The company was formerly known as American Reprographics Company and changed its name to ARC Document Solutions, Inc. in 2012. ARC Document Solutions, Inc. was founded in 1988 is headquartered in San Ramon, California.")
    (headlines ("")) (profit_margin 4.1) (gross_profit 96M)
    (diluted_eps 0.25))
   ((symbol MODV) (name "ModivCare Inc. (MODV)") (price 37.88) (growth 7.07)
    (sector Healthcare) (industry "Medical Care Facilities")
    (summary
     "ModivCare Inc., a technology-enabled healthcare services company, provides a suite of integrated supportive care solutions for public and private payors and their members. The company operates through four segments: Non-Emergency Medical Transportation (NEMT), Personal Care, Remote Patient Monitoring (RPM), and Corporate and Other. The company offers risk underwriting, contact center management, network credentialing, claims management, and non-emergency medical transport management services for Medicaid or Medicare eligible members, whose limited mobility or financial resources hinder their ability to access necessary healthcare and social services. It also provides in-home personal care services, such as bathing, personal hygiene, grooming, oral care, dressing, medication reminders, meal planning, preparation and feeding, housekeeping, transportation services, prescription reminders, and assistance with dressing and ambulation services through placing non-medical personal care assistants, home health aides, and skilled nurses primarily to Medicaid patients in need of care monitoring and assistance in performing daily living activities, including senior citizens and disabled adults. Ina addition, the company offers remote patient monitoring solutions, including personal emergency response systems, vitals monitoring, medication management, and data-driven patient engagement solutions. It serves federal, state, and local government agencies, MCOs, commercial insurers, private individuals, and health systems. The company was formerly known as The Providence Service Corporation and changed its name to ModivCare Inc. in January 2021. ModivCare Inc. was incorporated in 1996 and is based in Denver, Colorado.")
    (headlines ("")) (profit_margin -8.6) (gross_profit 472.32M)
    (diluted_eps -2.57))
   ((symbol SGTX) (name "Sigilon Therapeutics, Inc. (SGTX)") (price 23)
    (growth 6.43) (sector Healthcare) (industry Biotechnology)
    (summary
     "Sigilon Therapeutics, Inc., a preclinical stage biotechnology company, develops functional cures for patients with acute and chronic diseases. Its lead product candidate is SIG-002 to replace islet cells for the treatment of type 1 diabetes; and SIG-001, which is in Phase I/II clinical trial to prevent bleeding episodes in patients with moderate to severe Hemophilia A. The company is also developing SIG-205, SIG-218, SIG-220, and SIG-005, which are to treat the non-neurological manifestations of mucopolysaccharidosis type 1; and SIG-207 is to treat of Fabry disease. Sigilon Therapeutics, Inc. has a research collaboration and license agreement with Eli Lilly and Company for the development and commercialization of SLTx product candidates for the treatment of Type 1 Diabetes. The company was formerly known as Sigilon, Inc. and changed its name to Sigilon Therapeutics, Inc. in June 2017. Sigilon Therapeutics, Inc. was incorporated in 2015 and is headquartered in Cambridge, Massachusetts.")
    (headlines ("")) (profit_margin -253.3) (gross_profit -24.69M)
    (diluted_eps -14.83))
   ((symbol UTI) (name "Universal Technical Institute, Inc. (UTI)")
    (price 7.83) (growth 6.1) (sector "Consumer Defensive")
    (industry "Education & Training Services")
    (summary
     "Universal Technical Institute, Inc. provides transportation and technical training programs in the United States. It offers certificate, diploma, or degree programs under various brands, such as Universal Technical Institute, Motorcycle Mechanics Institute and Marine Mechanics Institute, NASCAR Technical Institute, and MIAT College of Technology. The company also provides manufacturer specific advanced training programs, including student paid electives at its campuses; and manufacturer or dealer sponsored training at various campuses and dedicated training centers, as well as offers programs for welding and CNC machining. As of September 30, 2022, it operated 16 campuses. Universal Technical Institute, Inc. was founded in 1965 and is headquartered in Phoenix, Arizona.")
    (headlines ("")) (profit_margin 1.9) (gross_profit 246.94M)
    (diluted_eps 0.09))
   ((symbol HMST) (name "HomeStreet, Inc. (HMST)") (price 11.1) (growth 5.51)
    (sector "Financial Services") (industry "Banks\226\128\148Regional")
    (summary
     "HomeStreet, Inc. operates as the bank holding company for HomeStreet Bank that provides commercial, mortgage, and consumer/retail banking services primarily in the Western United States. The company offers personal and business checking, savings accounts, interest-bearing, money market accounts, and certificates of deposit; credit cards; insurance; and cash management services. Its loan products include commercial real estate (CRE), multifamily, construction and land development, owner occupied CRE and commercial business loans; and single family, home equity, and other loans. In addition, the company offers online, mobile, and telephone banking. HomeStreet, Inc. serves small and medium sized businesses, real estate investors, professional firms, and individuals. The company was formerly known as Continental Mortgage and Loan Company. HomeStreet, Inc. was incorporated in 1921 and is headquartered in Seattle, Washington.")
    (headlines ("")) (profit_margin 0.9) (gross_profit 290.08M)
    (diluted_eps 3.07))
   ((symbol GHM) (name "Graham Corporation (GHM)") (price 15.83)
    (growth 13.48) (sector Industrials)
    (industry "Specialty Industrial Machinery")
    (summary
     "Graham Corporation, together with its subsidiaries, designs and manufactures fluid, power, heat transfer, and vacuum equipment for chemical and petrochemical processing, defense, space, petroleum refining, cryogenic, energy, and other industries. It offers power plant systems, including ejectors and surface condensers; torpedo ejection, propulsion, and power systems, such as turbines, alternators, regulators, pumps, and blowers; and thermal management systems comprising pumps, blowers, and drive electronics for defense sector. The company also provides rocket propulsion systems consisting of turbopumps and fuel pumps; cooling systems, which include pumps, compressors, fans, and blowers; and life support systems that comprise fans, pumps, and blowers for space industry. In addition, it offers heat transfer and vacuum systems, including ejectors, process and surface condensers, liquid ring pumps, heat exchangers, and nozzles; power generation systems, such as turbines, generators, compressors, and pumps; and thermal management systems comprising pumps, blowers, and electronics for energy sector. Further, the company offers heat transfer and vacuum systems consisting of ejectors, process and surface condensers, liquid ring pumps, heat exchangers, and nozzles for chemical and petrochemical processing industry. The company also services and sells spare parts for its equipment. It sells its products directly in the United States, the Middle East, Canada, Asia, South America, and internationally. Graham Corporation was founded in 1936 and is headquartered in Batavia, New York.")
    (headlines ("")) (profit_margin 0.2) (gross_profit N/A)
    (diluted_eps 0.03))
   ((symbol LEJU) (name "Leju Holdings Limited (LEJU)") (price 2.44)
    (growth 7.96) (sector "Real Estate") (industry "Real Estate Services")
    (summary
     "Leju Holdings Limited, through its subsidiaries, provides online to offline (O2O) real estate services in the People's Republic of China. It offers real estate e-commerce, online advertising, and online listing services through its online platform, and various mobile applications. The company also operates various real estate and home furnishing Websites of SINA Corporation (SINA). Its O2O services for new residential properties include selling discount coupons; and facilitating online property viewing, physical property visits, marketing events, and pre-sale customer support, as well as provides information platform to individual brokers. In addition, the company sells advertising primarily on the SINA new residential properties and home furnishing websites; and acts as an advertising agent for the SINA home page and non-real estate Websites with respect to advertising sold to real estate developers and home furnishing suppliers. Further, it offers fee-based online property listing services to real estate agents; and services to individual property sellers. The company was incorporated in 2013 and is headquartered in Beijing, the People's Republic of China.")
    (headlines ("")) (profit_margin -26.1) (gross_profit 312.58M)
    (diluted_eps -6.63))
   ((symbol LCUT) (name "Lifetime Brands, Inc. (LCUT)") (price 6.5)
    (growth 10.54) (sector "Consumer Cyclical")
    (industry "Furnishings, Fixtures & Appliances")
    (summary
     "Lifetime Brands, Inc. designs, sources, and sells branded kitchenware, tableware, and other products for use in the home in the United States and internationally. The company provides kitchenware products, including kitchen tools and gadgets, cutlery, kitchen scales, thermometers, cutting boards, shears, cookware, pantryware, spice racks, and bakeware; and tableware products comprising dinnerware, stemware, flatware, and giftware. It also provides home solutions, such as thermal beverageware, bath scales, weather and outdoor household, food storage, neoprene travel, and home d\195\169cor products. The company owns or licenses various brands, including Farberware, Mikasa, Taylor, KitchenAid, Pfaltzgraff, BUILT NY, Rabbit, Kamenstein, Sabatier, S'well, and Fred & Friends. It serves mass market merchants, specialty stores, commercial stores, department stores, warehouse clubs, grocery stores, off-price retailers, food service distributors, pharmacies, food and beverage outlets, and e-commerce. The company sells its products directly, as well as through its own websites. Lifetime Brands, Inc. was founded in 1945 and is headquartered in Garden City, New York.")
    (headlines ("")) (profit_margin -2.6) (gross_profit 260.32M)
    (diluted_eps -0.68))
   ((symbol GNE) (name "Genie Energy Ltd. (GNE)") (price 14.58) (growth 6.66)
    (sector Utilities) (industry "Utilities\226\128\148Regulated Electric")
    (summary
     "Genie Energy Ltd., through its subsidiaries, supplies electricity and natural gas to residential and small business customers in the United States and internationally. It operates in two segments, Genie Retail Energy and Genie Renewables. The company also develops, constructs, and operates solar energy projects for commercial and industrial customers, as well as its own portfolio; provides energy advisory and brokerage services; and manufactures and distributes solar panel, as well as engages in solar installation design and project management activities. Genie Energy Ltd. was incorporated in 2011 and is headquartered in Newark, New Jersey.")
    (headlines ("")) (profit_margin 25.1) (gross_profit 154.78M)
    (diluted_eps 1.96))
   ((symbol LINC) (name "Lincoln Educational Services Corporation (LINC)")
    (price 8.61) (growth 19.58) (sector "Consumer Defensive")
    (industry "Education & Training Services")
    (summary
     "Lincoln Educational Services Corporation, together with its subsidiaries, provides various career-oriented post-secondary education services to high school graduates and working adults in the United States. The company operates in two segments: Transportation and Skilled Trades, and Healthcare and Other Professions. It offers associate's degree, and diploma and certificate programs in automotive technology; skilled trades programs, including electrical, heating and air conditioning repair, welding, computerized numerical control, and electrical and electronic systems technology; health science programs comprising s licensed practical nurse, registered nurse, dental assistant, medical assistant, medical administrative assistant, and claims examiner; hospitality service programs, such as culinary, therapeutic massage, cosmetology, and aesthetics; and information technology programs. The company operates schools under the Lincoln Technical Institute, Lincoln College of Technology, Lincoln Culinary Institute, Euphoria Institute of Beauty Arts and Sciences, and other brand names. Lincoln Educational Services Corporation was founded in 1946 and is based in Parsippany, New Jersey.")
    (headlines ("")) (profit_margin 3.4) (gross_profit 199.54M)
    (diluted_eps 0.37))
   ((symbol GASS) (name "StealthGas Inc. (GASS)") (price 5.75) (growth 11.11)
    (sector Industrials) (industry "Marine Shipping")
    (summary
     "StealthGas Inc., together with its subsidiaries, provides seaborne transportation services to liquefied petroleum gas (LPG) producers and users worldwide. It also offers crude oil and natural gas. The company's carriers carry various petroleum gas products in liquefied form, including propane, butane, butadiene, isopropane, propylene, and vinyl chloride monomer, as well as ammonia; and refined petroleum products, such as gasoline, diesel, fuel oil, and jet fuel, as well as edible oils and chemicals. As of April 4, 2023, it had a fleet of 36 LPG carriers with a total capacity of 297,841 cubic meters. StealthGas Inc. was incorporated in 2004 and is based in Athens, Greece.")
    (headlines ("")) (profit_margin 28) (gross_profit 72.68M)
    (diluted_eps 1.13))
   ((symbol GRCL) (name "Gracell Biotechnologies Inc. (GRCL)") (price 3.83)
    (growth 11.99) (sector Healthcare) (industry Biotechnology)
    (summary
     "Gracell Biotechnologies Inc., a clinical-stage biopharmaceutical company, primarily discovers and develops cell therapies for the treatment of cancer in the People's Republic of China. Its lead product candidates include GC012F, a FasTCAR-enabled dual BCMA- and CD19-directed autologous CAR-T product candidate that is in Phase I trial for the treatment of multiple myeloma; GC019F, a FasTCAR-enabled CD19-directed autologous CAR-T product candidate, which is in Phase I clinical trial for the treatment of adult B cell acute lymphoblastic leukemia (B-ALL), as well as in phase 1 clinical trial for the treatment of relapsed or refractory (r/r) B cell  acute lymphoblastic leukemia (B-ALL) in adult; and GC027, a TruUCAR-enabled CD7-directed allogeneic CAR-T product candidate, which is in Phase I clinical trial for the treatment of adult T cell acute lymphoblastic leukemia. The company's product candidates also comprise GC007g, a donor-derived CD19-directed allogeneic CAR-T cell therapy that is in Phase 2 clinical trial for the treatment of r/r B-ALL; and GC502, a TruUCAR-enabled dual CD19- and CD7 -directed, off-the-shelf allogeneic CAR-T product candidate, which is in Phase I trial for the treatment of B-cell malignancies. In addition, it has a portfolio of earlier stage product candidates targeting various cancer indications, such as hematologic cell malignancies and solid tumors. Gracell Biotechnologies Inc. was incorporated in 2017 and is headquartered in Suzhou, China.")
    (headlines ("")) (profit_margin 0) (gross_profit N/A)
    (diluted_eps -1.14))
   ((symbol SENEA) (name "Seneca Foods Corporation (SENEA)") (price 40.55)
    (growth 5.08) (sector "Consumer Defensive") (industry "Packaged Foods")
    (summary
     "Seneca Foods Corporation provides packaged fruits and vegetables in the United States and internationally. It operates through three segments: Fruits and Vegetables, Prepared Food Products, and Snack Products. The company offers canned, frozen, and bottled produce; jarred fruit; and snack chips and other food products under the private label, as well as under various national and regional brands that the company owns or licenses, including Seneca, Libby's, Aunt Nellie's, Cherryman, Green Valley, and READ. In addition, it packs canned and frozen vegetables under contract packing agreements. Further, the company engages in the sale of cans, ends, and seeds, as well as trucking and aircraft operations. It provides its products to grocery outlets, including supermarkets, mass merchandisers, limited assortment stores, club stores, and dollar stores; specialty retailers; and food service distributors, restaurant chains, industrial markets, other food packagers, and export customers in 60 countries, as well as federal, state, and local governments for school and other feeding programs. Seneca Foods Corporation was incorporated in 1949 and is headquartered in Fairport, New York.")
    (headlines ("")) (profit_margin 0.6) (gross_profit 135.9M)
    (diluted_eps 4.17))
   ((symbol ARL) (name "American Realty Investors, Inc. (ARL)") (price 19.02)
    (growth 0.47) (sector "Real Estate")
    (industry "Real Estate\226\128\148Development")
    (summary
     "American Realty Investors, Inc., together with its subsidiaries, acquires, develops, and owns multifamily apartment communities and commercial real estate properties in the southwestern, southeastern, and mid-western United States. The company leases apartment units to residents; and leases office, industrial, and retail space to various for-profit businesses, as well as local, state, and federal agencies; and sells land and properties. As of December 31, 2021, its portfolio included five commercial properties comprising four office buildings and one retail properties; nine multifamily apartment communities consisting of 1,492 units; and fifty-two multifamily apartment communities totaling 10,281 units. The company also owns or controls 1,886 acres of developed and undeveloped land. American Realty Investors, Inc. was founded in 1999 and is headquartered in Dallas, Texas.")
    (headlines ("")) (profit_margin 71.8) (gross_profit 488.47M)
    (diluted_eps 22.78))
   ((symbol LTCH) (name "Latch, Inc. (LTCH)") (price 0.94) (growth 8.05)
    (sector Technology) (industry "Software\226\128\148Application")
    (summary
     "Latch, Inc. operates as an enterprise technology company in the United States and Canada. The company offers LatchOS, an operating system that extends smart access, delivery and guest management, smart home and sensors, connectivity, and personalization and services. Its software products include Latch Resident Mobile Applications, Latch Manager Web, and the Latch Manager Mobile Applications. The company also offers hardware devices that include M, C, and R series door-mounted access control products; Latch Intercom, which integrates into the Latch core access systems and allows audio and video calls for remote unlocking; Latch Camera, a dome camera; Latch Hub, a connectivity solution that enables smart access, smart home, and sensor devices at various buildings; and Latch Leak Detector, a solution to enable leak prevention, detection, and resolution for building owners and residents. In addition, it provides NFC unlock on Android that allows the user to unlock their door without even opening their phone; Latch Visitor Express, a contactless visitor entry system; and LatchID, an identification system. The company is headquartered in New York, New York.")
    (headlines ("")) (profit_margin 0) (gross_profit -2.68M)
    (diluted_eps -1.15))
   ((symbol NBTX) (name "Nanobiotix S.A. (NBTX)") (price 7.96) (growth 8.89)
    (sector Healthcare) (industry Biotechnology)
    (summary
     "Nanobiotix S.A., a clinical-stage biotechnology, focuses on developing product candidates for the treatment of cancer and other unmet medical needs. Its lead product candidate is NBTXR3, a sterile aqueous suspension of crystalline hafnium oxide nanoparticles used for the treatment of soft tissue sarcoma, head and neck cancers, liver cancers, prostate cancer, pancreatic cancer, esophageal cancer, rectal cancer, and non-small cell lung cancer. Nanobiotix S.A. has a partnership with Lian Oncology Limited to develop and commercialize NBTXR3 in Greater China, South Korea, Singapore, and Thailand. Nanobiotix S.A. was incorporated in 2003 and is headquartered in Paris, France.")
    (headlines ("")) (profit_margin 0) (gross_profit 4.78M)
    (diluted_eps -1.69))
   ((symbol GNFT) (name "Genfit S.A. (GNFT)") (price 3.88) (growth 4.3)
    (sector Healthcare) (industry Biotechnology)
    (summary
     "Genfit S.A., a biopharmaceutical company, discovers and develops drug candidates and diagnostic solutions for metabolic and liver-related diseases. The company develops Elafibranor, which is in Phase III clinical trial to treat patients with primary biliary cholangitis. It also engages in the development of NIS4 technology for the diagnosis of nonalcoholic steatohepatitis (NASH) and fibrosis; VS-01 for the treatment of Urea Cycle Disorder (UCD) and Organic Acidemia Disorder (OAD); GNS561, which is in Phase 1b/2 trial to treat patients with cholangiocarcinoma (CCA); and VS-01-ACLF and Nitazoxanide (NTZ), which is in Phase 1 trial to treat acute-on-chronic liver failure, as well as VS-02-HE, which is in preclinical trial for the treatment of Reduction of Hyperammonemia and the Stabilization of Blood Ammonia. The company has a licensing agreement with Labcorp for the commercialization of NASHnext, a blood-based molecular diagnostic test; and Genoscience Pharma to develop and commercialize the investigational treatment GNS561 for CCA. The company was incorporated in 1999 and is headquartered in Loos, France.")
    (headlines ("")) (profit_margin -90.3) (gross_profit 26.25M)
    (diluted_eps -0.52))
   ((symbol GTN-A) (name "Gray Television, Inc. (GTN-A)") (price 10.45)
    (growth 0.76) (sector "Communication Services") (industry Broadcasting)
    (summary
     "Gray Television, Inc., a television broadcasting company, owns and/or operates television stations and digital assets in the United States. It also broadcasts secondary digital channels affiliated to ABC, CBS, NBC, and FOX, as well as various other networks and program services, including CW Plus Network, MY Network, the MeTV Network, Circle, Antenna TV, Telemundo, and Cozi; and local news/weather channels in various markets. In addition, the company offers video program production services. It owns and operates television stations and digital assets that serve television markets in the United States. The company was formerly known as Gray Communications Systems, Inc. and changed its name to Gray Television, Inc. in August 2002. Gray Television, Inc. was founded in 1891 and is headquartered in Atlanta, Georgia.")
    (headlines ("")) (profit_margin 7.4) (gross_profit 1.43B)
    (diluted_eps 3.34))
   ((symbol SONX) (name "Sonendo, Inc. (SONX)") (price 1.31) (growth 10.08)
    (sector Healthcare) (industry "Medical Devices")
    (summary
     "Sonendo, Inc., a commercial-stage medical technology company, develops, manufactures, and commercializes devices for root canal therapy in the United States and Canada. It provides GentleWave, a tooth decay treatment, a technology platform designed for cleaning and disinfecting the microscopic spaces within teeth without the need to remove tooth structure. The company also offers SoundSeal, a material used to build and create a sealing platform on the top of the crown; and Sonendo-branded liquid solution of ethylenediaminetetraacetic acid EDTA that is used to help debride and disinfect the root canal system. In addition, it provides The Digital Office, a practice management software to enable an integrated digital office for dental practitioners. The company was formerly known as Dentatek Corporation and changed its name to Sonendo, Inc. in March 2011. Sonendo, Inc. was incorporated in 2006 and is headquartered in Laguna Hills, California.")
    (headlines ("")) (profit_margin -131.2) (gross_profit 10.48M)
    (diluted_eps -0.96))
   ((symbol COCO) (name "The Vita Coco Company, Inc. (COCO)") (price 27.59)
    (growth 12.25) (sector "Consumer Defensive")
    (industry "Beverages\226\128\148Non-Alcoholic")
    (summary
     "The Vita Coco Company, Inc. develops, markets, and distributes coconut water products under the Vita Coco brand name in the United States, Canada, Europe, the Middle East, and the Asia Pacific. The company offers coconut oil and coconut milk; Hydration Drink Mix, a powdered form of flavored coconut water; sparkling water; Runa, a plant-based energy drink; purified water under the Ever & Ever brand name; and PWR LIFT, a protein-infused fitness drink. It distributes its products through club, food, drug, mass, convenience, e-commerce, and foodservice channels. In addition, the company supplies coconut water and coconut oil categories to retailers. The company was formerly known as All Market Inc. and changed its name to The Vita Coco Company, Inc. in September 2021.The Vita Coco Company, Inc. was founded in 2004 and is headquartered in New York, New York.")
    (headlines ("")) (profit_margin 6.2) (gross_profit 103.36M)
    (diluted_eps 0.22))
   ((symbol MYNA) (name "Mynaric AG (MYNA)") (price 5.68) (growth 8.11)
    (sector Technology) (industry "Communication Equipment")
    (summary
     "Mynaric AG develops and manufactures advanced laser communication technology for long-distance data transmission between moving objects for wireless terrestrial, airborne, and space applications in the United States, Canada, and Belgium. The company offers CONDOR, an optical inter-satellite link flight terminal for satellite-to-satellite communications in space; and HAWK, an airborne flight terminal for air-to-air and air-to-ground links of airborne vehicles. Its products provide connectivity solutions to link satellites, high-altitude platforms, unmanned aerial vehicles, and aircraft. Mynaric AG was incorporated in 2009 and is headquartered in Gilching, Germany.")
    (headlines ("")) (profit_margin 0) (gross_profit -8.69M)
    (diluted_eps -3.82))
   ((symbol RBT) (name "Rubicon Technologies, Inc. (RBT)") (price 1.13)
    (growth 10.78) (sector Technology)
    (industry "Software\226\128\148Application")
    (summary
     "Rubicon Technologies, Inc., a digital marketplace for waste and recycling services, provides cloud-based waste and recycling solutions to businesses, governments, and organizations worldwide. The company provides solutions for waste generators; and haulers and recyclers. It offers consultation and management services to customers for waste removal, waste management, logistics, and recycling solutions. Its consultation and management services include planning, consolidation of billing and administration, cost savings analyses, and vendor performance monitoring and management. In addition, the company offers logistics services; and markets and resells recyclable commodities. Rubicon Technologies, Inc. was founded in 2008 and is headquartered in Lexington, Kentucky.")
    (headlines ("")) (profit_margin -1.2) (gross_profit 27.55M)
    (diluted_eps -0.42))
   ((symbol METCB) (name "Ramaco Resources, Inc. (METCB)") (price 13.44)
    (growth 9.27) (sector "Basic Materials") (industry "Coking Coal")
    (summary
     "Ramaco Resources, Inc. operates, develops, and sells metallurgical coal. Its development portfolio includes the Elk Creek project located in southern West Virginia; the Berwind property situated on the border of West Virginia and Virginia; the Knox Creek property is located in Virginia; and the RAM Mine property situated in southwestern Pennsylvania. The company serves blast furnace steel mills and coke plants in the United States, as well as international metallurgical coal consumers. The company was founded in 2015 and is headquartered in Lexington, Kentucky.")
    (headlines ("")) (profit_margin 17.3) (gross_profit 232.73M)
    (diluted_eps 2.68))
   ((symbol TMC) (name "TMC the metals company Inc. (TMC)") (price 1.26)
    (growth 13.51) (sector "Basic Materials")
    (industry "Other Industrial Metals & Mining")
    (summary
     "TMC the metals company Inc., a deep-sea minerals exploration company, focuses on the collection, processing, and refining of polymetallic nodules found on the seafloor in the Clarion Clipperton Zone (CCZ) in the south-west of San Diego, California. It primarily explores for nickel, cobalt, copper, and manganese products. The company holds exploration and commercial rights in three polymetallic nodule contract areas in the CCZ of the Pacific Ocean. Its products are used in electric vehicles (EV), renewable energy storage markets, EV wiring, clean energy transmission, manganese alloy production required for steel production, and other applications. The company was formerly known as Sustainable Opportunities Acquisition Corporation and changed its name to TMC the metals company Inc. TMC the metals company Inc. was incorporated in 2019 and is based in Vancouver, Canada.")
    (headlines ("")) (profit_margin 0) (gross_profit N/A)
    (diluted_eps -0.64))
   ((symbol CCSI) (name "Consensus Cloud Solutions, Inc. (CCSI)")
    (price 32.06) (growth 5.15) (sector Technology)
    (industry "Software\226\128\148Infrastructure")
    (summary
     "Consensus Cloud Solutions, Inc., together with its subsidiaries, provides information delivery services with a software-as-a-service platform worldwide. It offers eFax Corporate, a digital cloud-fax technology; Unite, a single platform that allows the user to choose between various protocols to send and receive healthcare information and can integrate into an existing electronic health record system or stand-alone if no EHR is present; jsign, an electronic and digital signature solution; Conductor, an interface engine and interoperability platform that provides integration technology; Clarity that transforms unstructured documents into structured actionable data; and eFax, an online faxing solution, as well as other products under the MyFax, MetroFax, Sfax, and SRfax brands. It serves healthcare, government, financial services, law, and education industries. Consensus Cloud Solutions, Inc. was incorporated in 2021 and is headquartered in Los Angeles, California.")
    (headlines ("")) (profit_margin 19.1) (gross_profit 300.47M)
    (diluted_eps 3.5))
   ((symbol TXO) (name "TXO Partners L.P. (TXO)") (price 22.2) (growth 5.71)
    (sector Energy) (industry "Oil & Gas E&P")
    (summary
     "TXO Partners L.P. focuses on the acquisition, development, optimization, and exploitation of conventional oil, natural gas, and natural gas liquid reserves in North America. Its acreage positions are concentrated in the Permian Basin of West Texas and New Mexico and the San Juan Basin of New Mexico and Colorado. The company was formerly known as TXO Energy Partners, L.P. and changed its name to TXO Partners L.P. in May 2023. TXO Partners L.P. was incorporated in 2012 and is based in Fort Worth, Texas.")
    (headlines ("")) (profit_margin 34.2) (gross_profit N/A)
    (diluted_eps 4.71))
   ((symbol FIHL) (name "Fidelis Insurance Holdings Limited (FIHL)")
    (price 14.11) (growth 5.22) (sector "Financial Services")
    (industry "Insurance\226\128\148Diversified")
    (summary
     "Fidelis Insurance Holdings Limited, together with its subsidiaries, provides insurance and reinsurance products in Bermuda, Ireland, and the United Kingdom. It operates in three segments: Specialty, Reinsurance, and Bespoke segments. The Specialty segment offers aviation and aerospace, energy, marine, property direct and facultative, and other specialty risk solutions. The Reinsurance segment provides property, retrocession, and whole account reinsurance solutions. The Bespoke segment offers customized risk solutions for clients that include credit and political risk, and other risk transfer opportunities. The company is also involved in specialty treaty reinsurance, and surety bonds and guarantees activities; and upstream energy, energy liability, and marine businesses; and provision of product recall and contamination, and marketing services. Fidelis Insurance Holdings Limited was incorporated in 2014 and is headquartered in Pembroke, Bermuda.")
    (headlines ("")) (profit_margin 54.4) (gross_profit 235.7M)
    (diluted_eps 29.16)))))
